Для датафрейма log из материалов занятия создайте столбец source_type по правилам:
-если источник traffic_source равен Yandex или Google, то в source_type ставится organic;
-для источников paid и email из России ставим ad;
-для источников paid и email не из России ставим other;
-все остальные варианты берём из traffic_source без изменений.

In [12]:
import pandas as pd
import re

In [7]:
visit_log = pd.read_csv("vlog.csv", encoding="utf-8", sep=";")
visit_log["source_type"] = visit_log["traffic_source"]
visit_log.loc[visit_log["traffic_source"].isin(["yandex", "google"]), "source_type"] = "organic"
visit_log.loc[visit_log["traffic_source"].isin(["yandex", "google"]) & (visit_log["region"] == "Russia"), "source_type"] = "ad"
visit_log.loc[visit_log["traffic_source"].isin(["yandex", "google"]) & (visit_log["region"] != "Russia"), "source_type"] = "other"
visit_log.head()

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,ad
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,ad
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,ad
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,ad

В файле URLs.txt содержатся URL страниц новостного сайта. Вам нужно отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри URL конструкцию: /, затем 8 цифр, затем дефис. Выполните действия:

-Прочитайте содержимое файла с датафрейм.
-Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствие с заданным шаблоном.

In [ ]:
urls = pd.read_csv("URLs.txt", encoding="utf-8")
urls_news = urls[urls['url'].str.contains(r'/\d{8}-', regex=True, na=False)].reset_index(drop=True)
urls_news.head()

                                                  url
0   /politics/36188461-s-marta-zhizn-rossiyan-susc...
1   /world/36007585-tramp-pridumal-kak-reshit-ukra...
2   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
3   /video/36001498-poyavilis-pervye-podrobnosti-g...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
79  /cis/35984145-kreml-prokommentiroval-soobschen...
80  /video/36071019-olimpiyskie-obekty-rio-prevrat...
81  /science/36151301-nazvano-posledstvie-zloupotr...
82  /incidents/36027330-vospitatelnitsu-zatravili-...
83  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]